services:
  - host: "http://localhost:8080"
    trustAllCerts: true
    endpoints:
      - path: /ping
        verb: "GET"
        statusCodes:
          - 200
        changes:
          - type: add
            field: proxy
            value: works
